"""
Aegis Universal Test Runner Contracts & Capability Models
Defines the universal runner protocol, capability declarations, execution contexts,
and runner plan/result contracts.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from enum import Enum
from pathlib import Path
from typing import Dict, Any, List, Optional, Set
from pydantic import BaseModel, Field

from aegis.evidence.models import TestResult, TestStatus, ArtifactRef


class RunnerCategory(str, Enum):
    UNIT = "unit"
    API = "api"
    SANITY = "sanity"
    INTEGRATION = "integration"
    E2E = "e2e"
    UI = "ui"
    UX = "ux"
    ACCESSIBILITY = "accessibility"
    SECURITY = "security"
    PERFORMANCE = "performance"
    COMPATIBILITY = "compatibility"


class FailureClassification(str, Enum):
    DETERMINISTIC_FAILURE = "DETERMINISTIC_FAILURE"
    TRANSIENT_FAILURE = "TRANSIENT_FAILURE"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
    FLAKY_FAILURE = "FLAKY_FAILURE"
    TIMEOUT_FAILURE = "TIMEOUT_FAILURE"
    UNKNOWN = "UNKNOWN"


class RunnerCapability(BaseModel):
    """Declarative capability specification of a test runner."""
    name: str                                # E.g. "pytest", "vitest", "aegis_api_contract", "aegis_sanity"
    version: str = "1.0.0"
    categories: List[RunnerCategory] = Field(default_factory=list)
    supported_languages: List[str] = Field(default_factory=list)
    supported_frameworks: List[str] = Field(default_factory=list)
    required_tools: List[str] = Field(default_factory=list)     # CLI binaries needed, e.g. ["pytest"]
    required_services: List[str] = Field(default_factory=list)  # e.g. ["docker", "postgres"]
    supports_parallel: bool = True
    supports_retry: bool = True
    supports_targeted_execution: bool = True
    supports_dry_run: bool = True
    supports_artifacts: bool = True
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ExecutionContext(BaseModel):
    """Runtime context provided to a test runner for planning and execution."""
    workspace_root: str
    target_files: List[str] = Field(default_factory=list)
    target_symbols: List[str] = Field(default_factory=list)
    category: RunnerCategory = RunnerCategory.UNIT
    dry_run: bool = False
    timeout_seconds: int = 120
    correlation_id: str = "default_corr"
    trace_id: Optional[str] = None
    environment: Dict[str, str] = Field(default_factory=dict)
    options: Dict[str, Any] = Field(default_factory=dict)


class RunnerPlan(BaseModel):
    """Concrete execution instructions generated by a runner."""
    runner_name: str
    category: RunnerCategory
    command: List[str] = Field(default_factory=list)
    cwd: str
    env_vars: Dict[str, str] = Field(default_factory=dict)
    estimated_tests: int = 1
    timeout_seconds: int = 120
    is_targeted: bool = False
    target_descriptors: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TestRunner(ABC):
    """Universal abstract base class and protocol for all Aegis test and quality runners."""

    def __init__(self, workspace_root: Path | str) -> None:
        self.workspace_root = Path(workspace_root).resolve()

    @property
    @abstractmethod
    def capability(self) -> RunnerCapability:
        """Returns the declared capabilities of this runner."""
        pass

    @abstractmethod
    def supports(self, context: ExecutionContext) -> bool:
        """Evaluates whether this runner can execute the given context."""
        pass

    @abstractmethod
    def plan(self, context: ExecutionContext) -> RunnerPlan:
        """Produces a deterministic execution plan for the context."""
        pass

    @abstractmethod
    def execute(self, plan: RunnerPlan, context: ExecutionContext) -> List[TestResult]:
        """Executes the plan and returns standardized machine-verifiable TestResults."""
        pass

    def cancel(self) -> None:
        """Handles cancellation of active execution if running."""
        pass
